name: Deploy

env:
  DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

on:
    push:
      branches: [main]
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Deploy
          run: curl "$DEPLOY_URL"